**fly.toml**
```toml
app = "apex-ytsum"
primary_region = "bom"

[build]

[env]
  PORT = "8000"
  OPENAI_MODEL = "gpt-4o-mini"
  USE_LOCAL_WHISPER = "0"

[[services]]
  internal_port = 8000
  processes = ["app"]
  protocol = "tcp"
  auto_start_machines = true
  auto_stop_machines = true
  min_machines_running = 0

  [[services.ports]]
    handlers = ["http"]
    port = 80
  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

  [[services.tcp_checks]]
    interval = "15s"
    timeout = "2s"
    grace_period = "20s"

[checks]
  [checks.health]
    type = "http"
    port = 8000
    interval = "15s"
    timeout = "2s"
    grace_period = "20s"
    method = "get"
    path = "/health"